config/routes.rb
Bulletin::Application.routes.draw do

  devise_for :users
  resources :dashboard, :posts, :profiles, :friendships, :my_bulletins, :activities

  root to: 'home#index'

  

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :user_id, :friend_id

  validates_uniqueness_of :user_id, :scope => [:friend_id]

  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/models/my_bulletin.rb
class MyBulletin < ActiveRecord::Base
  include PublicActivity::Model
  
  tracked owner: ->(controller, model) { controller && controller.current_user }

  attr_accessible :title

  has_many :post
  belongs_to :user, dependent: :destroy
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :description, :duedate, :title, :photo, :user_id

  include PublicActivity::Common

  belongs_to :user
  belongs_to :my_bulletin

  has_attached_file :photo, :styles => { :small => "150x150>" },
                  :url  => "/assets/posts/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/posts/:id/:style/:basename.:extension"

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

  validates :title, presence: true, uniqueness: true

  validates :description, presence: true

  validates :duedate, presence: true

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :user_id

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts, dependent: :destroy

  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  has_one :profile, dependent: :destroy
  has_one :my_bulletin, dependent: :destroy

  accepts_nested_attributes_for :profile
  accepts_nested_attributes_for :my_bulletin

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :profile_attributes, :my_bulletin_attributes
  # attr_accessible :title, :body
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
  	@activities = PublicActivity::Activity.order("created_at desc").where(owner_id: current_user.friend_ids, owner_type: "User")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include PublicActivity::StoreController
  protect_from_forgery

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	before_filter :authenticate_user!

	def index
		@profile= current_user.profile
		@bulletin = current_user.my_bulletin
	end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  

  def create
    @friendship = current_user.friendships.create(:friend_id => params[:friend_id])
    if @friendship.save
      flash[:notice] = "Added friend."
      redirect_to root_url
    else
      flash[:error] = "Unable to add friend."
      redirect_to root_url
    end
  end 

  def destroy
    @friendship = current_user.friendships.find(params[:id])
    @friendship.destroy
    flash[:notice] = "Removed friendship."
    redirect_to root_url
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		if user_signed_in?
			redirect_to :controller => 'dashboard', :action => 'index'
		end
	end

end

app/controllers/my_bulletins_controller.rb
class MyBulletinsController < ApplicationController

  	def show
		@bulletin = MyBulletin.find(params[:id])
		@posts = Post.where(:posts => { :user_id => @bulletin.user_id})
	end

	def create
	  @bulletin = Bulletin.new(params[:my_bulletin])
	  if @bulletin.save
	    redirect_to root_url
	  else
	    render :action => 'user#new'
	  end
	end

	def edit
		@bulletin = Bulletin.find(params[:id])
	end

	def update
		@bulletin = Bulletin.find(params[:id])

		if @bulletin.update_attributes(params[:my_bulletin])
			redirect_to my_bulletins_path, :notice => "Your profile was updated"
		else
			render "edit"
		end
	end

	def destroy
		@bulletin = MyBulletin.find(params[:id])
		@bulletin.destroy
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		#@posts = Post.all
		@posts = Post.where(:posts => { :user_id => current_user.id})
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def create
		
		@post = Post.new(params[:post])

		@post.user_id = current_user.id

		@post.my_bulletins_id = current_user.my_bulletin.id

		if @post.save
			@post.create_activity :create, owner: current_user
			render "show", :notice => "Your post was saved"
		else
			render "new"
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update_attributes(params[:post])
			redirect_to posts_path, :notice => "Your post was updated"
		else
			render "edit"
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path, :notice => "your post has been deleted"
	end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController


	def show
		@profile = Profile.find(params[:id])
	end

	def create
	  @profile = Profile.new(params[:profile])
	  if @profile.save
	    redirect_to profile_path(@profile), :notice => 'User successfully added.'
	  else
	    render :action => 'user#new'
	  end
	end

	def edit
		@profile = Profile.find(params[:id])
	end

	def update
		@profile = Profile.find(params[:id])

		if @profile.update_attributes(params[:profile])
			redirect_to profiles_path, :notice => "Your profile was updated"
		else
			render "edit"
		end
	end

	def destroy
		@profile = Profile.find(params[:id])
		@profile.destroy
	end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def cp(path)
  		if current_page?(path)
  			puts "active"
  		end
	end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/my_bulletins_helper.rb
module MyBulletinsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/activities/index.html.erb
<h1>Friends&rsquo; Activities</h1>
<% @activities.each do |activity| %>
  <div class="activity">
    
    <%= render_activity activity %>
  </div>
<% end %>

app/views/dashboard/index.html.erb
 <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

			<div class="row" id="dashboard-row">
	            <div class="col-6 col-sm-6 col-lg-4 dash-tab">
	              <h2><%= link_to "Profile", @profile %></h2>
	              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
	              
	            </div><!--/span-->
	            <div class="col-6 col-sm-6 col-lg-4 dash-tab">
	              <h2><%= link_to "Newsfeed", activities_path %></h2>
	              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
	              
	            </div><!--/span-->
	            <div class="col-6 col-sm-6 col-lg-4 dash-tab">
	              <h2><%= link_to "BinIt", new_post_path %></h2>
	              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
	             
	            </div><!--/span-->
	            <div class="col-6 col-sm-6 col-lg-4 dash-tab">
	              <h2>Discover</h2>
	              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
	             
	            </div><!--/span-->
	            <div class="col-6 col-sm-6 col-lg-4 dash-tab">
	              <h2><%= link_to "My Bulletin", @bulletin %></h2>
	              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
	              
	            </div><!--/span-->
	            <div class="col-6 col-sm-6 col-lg-4 dash-tab">
	              <h2>Dashboard</h2>
	              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
	              
	            </div><!--/span-->
	          </div>
		</div>
	</div>
</div>

app/views/home/index.html.erb
 <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="inner cover">
            <h1 class="cover-heading">Bulletins made easy</h1>
            <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
            <p class="lead">
              <%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-lg btn-default" %>
            </p>
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p>Cover template for <a href="http://getbootstrap.com">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
            </div>
          </div>
</div>
</div>
</div>
        

app/views/my_bulletins/index.html.erb
<h1>MyBulletins#index</h1>
<p>Find me in app/views/my_bulletins/index.html.erb</p>

app/views/my_bulletins/show.html.erb
<h2><%= @bulletin.title %></h2>
<% @posts.each do |post| %>
	<h2> <%= link_to post.title, post %> </h2>
	<p><%= post.description %></p>
	<%= image_tag post.photo.url(:small) %>
	<% if post.user_id == current_user.id  %>
		<p><%= link_to "Edit", edit_post_path(post) %> | <%= link_to "Delete", post, :confirm => "Are you sure?", :method => :delete %></p>
	<% end %>
	<hr />
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_for @post do |f|%>

	<% if @post.errors.any? %>
		<h2>Errors:</h2>
		<ul>
			<% @post.errors.full_messages.each do |message| %>
				<li><%= message %> </li>
			<% end %>
		</ul>
	<% end %>
	
	<p>
		<%= f.label :title%><br>
		<%= f.text_field :title %>
	</p>	

	<p>
		<%= f.label :description%><br>
		<%= f.text_area :description %>
	</p>

	<p>
		<%= f.label :photo%><br>
		<%= f.file_field :photo %>
	</p>

	<p>
		<%= f.label :duedate%><br>
		<%= f.text_field :duedate, :class => "form-control", :placeholder => "yyyy-mm-dd", :autofocus => true %>
	</p>
	
	<p>
		<%= f.submit "Update Post"%>
	</p>

<% end %>

app/views/posts/index.html.erb
<h1>Index Post</h1>

<% @posts.each do |post| %>
	<h2> <%= link_to post.title, post %> </h2>
	<p><%= post.description %></p>
	<% if post.user_id == current_user.id  %>
		<p><%= link_to "Edit", edit_post_path(post) %> | <%= link_to "Delete", post, :confirm => "Are you sure?", :method => :delete %></p>
	<% end %>
	<hr />
<% end %>

<p><%= link_to "Add a new post", new_post_path %></p>

app/views/posts/new.html.erb
<h1>Add a New Post</h1>

<%= form_for @post, :html => { :multipart => true } do |f| %>

	<% if @post.errors.any? %>
		<h2>Errors:</h2>
		<ul>
			<% @post.errors.full_messages.each do |message| %>
				<li><%= message %> </li>
			<% end %>
		</ul>
	<% end %>

	<p>
		<%= f.label :title%><br>
		<%= f.text_field :title %>
	</p>	

	<p>
		<%= f.label :description%><br>
		<%= f.text_area :description %>
	</p>

	<p>
		<%= f.label :photo%><br>
		<%= f.file_field :photo %>
	</p>

	<p>
		<%= f.label :duedate%><br>
		<%= f.text_field :duedate, :class => "form-control", :placeholder => "yyyy-mm-dd", :autofocus => true %>
	</p>

	<p>
		<%= f.submit "Add a new post"%>
	</p>

<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.description %></p>
<%= image_tag @post.photo.url(:small) %>
<small><%= @post.created_at %></small>

app/views/profiles/show.html.erb
<h1><%= @profile.first_name %></h1>
<h1><%= @profile.last_name %></h1>

<h2>Friends</h2>
<ul>
  <% for friendship in User.find(Profile.find_by_id(params[:id]).user_id).friendships %>
    <li>
      <%=h friendship.friend.email%>
      <%if current_user == User.find(Profile.find_by_id(params[:id]).user_id)%>
        (<%= link_to "remove", friendship, :method => :delete %>)
      <% end %>
    </li>
  <% end %>
</ul>



<h2>Friended by Users</h2>
<ul>
  <% for user in User.find(Profile.find_by_id(params[:id]).user_id).inverse_friends %>
    <li><%=h user.email %></li>
  <% end %>
</ul>



<%if current_user.profile.id != @profile.id and current_user.friendships.where(friend_id: Profile.find_by_id(params[:id]).user_id).blank?%>
<%= link_to "Add Friend", friendships_path(:friend_id => Profile.find_by_id(params[:id]).user_id), :method => :post %>
<% end %>

app/views/public_activity/post/_create.html.erb
 
<% if activity.trackable %>
	<%= link_to activity.owner.profile.first_name, activity.owner.profile if activity.owner %> 
	added post to
  <%= link_to activity.owner.my_bulletin.title, activity.owner.my_bulletin%>
<% else %>
  <%= link_to activity.owner.profile.first_name, activity.owner.profile if activity.owner %>'s
  post has been (removed)
<% end %>